declare function log(msg: string): void;
declare function warn(msg: string): void;
declare function error(msg: string): void;
declare function info(msg: string): void;
declare function table(obj: object): void;
declare function time(label: string): void;
declare function timeEnd(label: string): void;
declare function timeLog(label: string | "default", operation: void | any): void;
declare function clear(): void;
declare function successLog(msg: string): void;
declare function warnLog(msg: string): void;
declare function errorLog(msg: string): void;
declare function infoLog(msg: string): void;
declare function successIconLog(msg: string): void;
declare function warnIconLog(msg: string): void;
declare function errorIconLog(msg: string): void;
declare function infoIconLog(msg: string): void;
declare function stringify(obj: object): void;
declare function parseJson(str: string): void;

export { clear, error, errorIconLog, errorLog, info, infoIconLog, infoLog, log, parseJson, stringify, successIconLog, successLog, table, time, timeEnd, timeLog, warn, warnIconLog, warnLog };
