export declare function log(msg: string): void;
export declare function warn(msg: string): void;
export declare function error(msg: string): void;
export declare function info(msg: string): void;
export declare function table(obj: object): void;
export declare function time(label: string): void;
export declare function timeEnd(label: string): void;
export declare function timeLog(label: string | "default", operation: void | any): void;
export declare function clear(): void;
export declare function successLog(msg: string): void;
export declare function warnLog(msg: string): void;
export declare function errorLog(msg: string): void;
export declare function infoLog(msg: string): void;
export declare function successIconLog(msg: string): void;
export declare function warnIconLog(msg: string): void;
export declare function errorIconLog(msg: string): void;
export declare function infoIconLog(msg: string): void;
export declare function stringify(obj: object): void;
export declare function parseJson(str: string): void;
